apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:32001/sigemad-frontend:develop-39bdd756d9564bf622d35740fe7e759f00dcc23b
          ports:
            - containerPort: 80
          #volumeMounts:
            #- name: nginx-html
              #mountPath: /usr/share/nginx/html
      #volumes:
        #- name: nginx-html
          #emptyDir: {}
