apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:32001/sigemad-frontend:main-04eba53b739b8ba6c45040f32c967486d3071434
          ports:
            - containerPort: 80
          #volumeMounts:
            #- name: nginx-html
              #mountPath: /usr/share/nginx/html
      #volumes:
        #- name: nginx-html
          #emptyDir: {}
