apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sigemad-api
  namespace: ns-sigemad
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: e42503c94401.ngrok.app
      http:
        paths:
          - path: /swagger(/.*)?
            pathType: Prefix
            backend:
              service:
                name: svc-backend
                port:
                  number: 8080
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: svc-backend
                port:
                  number: 8080
            # Agregar la anotación de reescritura aquí
            pathAnnotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2
