apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ns-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dsmarkromero/sigemad-back:v1.01
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__ConnectionString
              value: "Data Source=sqlserver;Initial Catalog=Sigemad;user id=sigemadUsr;password=Temporal01_;TrustServerCertificate=true"
            - name: ConnectionStrings__IdentityConnectionString
              value: "Data Source=sqlserver;Initial Catalog=SigemadSecurity;user id=sigemadUsr;password=Temporal01_;TrustServerCertificate=true"
